image: node:18
pipelines:
  branches:
    master:
      - step:
          name: Install Dependencies
          script:
            - npm install
      - step:
          name: Build TypeScript
          script:
            - npm install -g typescript
            - npx tsc
      - step:
          name: Deploy to Server
          script:
            - scp -r build/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
            - ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && npm install"
            - ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && pm2 reload rabbitConsumer"
