image: node:18
pipelines:
  branches:
    master:
      - step:
          name: Deploy to production
          script:
            - apt-get update && apt-get install -y rsync ssh
            - npm install
            - npm install -g typescript
            - tsc --skipLibCheck --resolveJsonModule --esModuleInterop --outDir build -t es5 Simulator/rabbitConsumer.ts
            - rsync -rzvP -r --exclude-from=.gitignore $BITBUCKET_CLONE_DIR/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
            - ssh $DEPLOY_USER@$DEPLOY_HOST "PATH=$PATH:/root/.nvm/versions/node/v18.12.1/bin && cd /root/bot && npm install"
            - ssh $DEPLOY_USER@$DEPLOY_HOST "PATH=$PATH:/root/.nvm/versions/node/v18.12.1/bin && cd $DEPLOY_PATH && pm2 reload rabbitConsumer"
