apiVersion: batch/v1
kind: Job
metadata:
  name: simulator
spec:
  template:
    spec:
      containers:
      - name: simulator
        image: registry.digitalocean.com/simulator-registery/simulator
        command: ["node", "Simulator/Simulate.js",  "7",
                "6395ac587669aa7822285531",
                "2022-11-04 14:02:51",
                "2022-12-01 14:02:51"]
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "trading-cloud.json"
        
      restartPolicy: Never
  completions: 10
  parallelism: 2
  backoffLimit: 4

